#######
# Compiled from data/unmd/functions/horsebones.mcscript
# to .//data/unmd/functions/horsebones/execute_as_horsebone.mcfunction
#
# Generated by Minecraft Script for 1.13
######

execute as @e[type=skeleton_horse,tag=horsebones_horsebone_main] at @s run function unmd:horsebones/horsebone_particle
