#######
# Compiled from data/unmd/functions/horsebones.mcscript
# to .//data/unmd/functions/horsebones/give_saddle_of_summoning.mcfunction
#
# Generated by Minecraft Script for 1.13
######

give @s minecraft:saddle{display:{Name:"{\"translate\":\"Saddle of Summoning\",\"italic\":false}",Lore:["Drop this to get Horsebone","Take this saddle out to make Horsebone dissapear"]},HideFlags:1,ench:[{id:70,lvl:1}]}
