#######
# Compiled from data/unmd/functions/horsebones.mcscript
# to .//data/unmd/functions/horsebones/horsebone_particle.mcfunction
#
# Generated by Minecraft Script for 1.13
######

execute as @e[type=skeleton_horse,tag=horsebones_horsebone_main] at @s positioned ~ ~1.55 ~ rotated ~ 0 run particle minecraft:flame ^ ^ ^1.35 0.1 0.1 0.1 0 1 force
