#######
# Compiled from data/unmd/functions/horsebones.mcscript
# to .//data/unmd/functions/horsebones/horsebone_maintain.mcfunction
#
# Generated by Minecraft Script for 1.13
######

execute as @e[type=skeleton_horse,tag=horsebones_horsebone_main] at @s run data merge entity @s {Attributes:[{Name:generic.maxHealth,Base:30},{Name:generic.movementSpeed,Base:0.3375},{Name:generic.jumpStrength,Base:10}]}
