#######
# Compiled from data/unmd/functions/horsebones.mcscript
# to .//data/unmd/functions/horsebones/kill_horsebone_detection.mcfunction
#
# Generated by Minecraft Script for 1.13
######

execute as @e[type=skeleton_horse,tag=horsebones_horsebone_main] at @s unless entity @s[nbt={SaddleItem: {id: "minecraft:saddle", Count: 1b, tag: {ench: [{lvl: 1, id: 70}], HideFlags: 1, display: {Lore: ["Drop this to get Horsebone", "Take this saddle out to make Horsebone dissapear"], Name: "{\"translate\":\"Saddle of Summoning\",\"italic\":false}"}}}}] run function unmd:horsebones/kill_horsebone
