#######
# Compiled from data/unmd/functions/horsebones.mcscript
# to .//data/unmd/functions/horsebones/load.mcfunction
#
# Generated by Minecraft Script for 1.13
######

scoreboard objectives add hbs_saddle_og dummy
scoreboard objectives add hbs_man_swap dummy Horseman swap weapons
bossbar create unmd:horsebones/horseman ["",{"text":"Horseman"}]
bossbar set unmd:horsebones/horseman visible false
bossbar set unmd:horsebones/horseman players @a
bossbar set unmd:horsebones/horseman max 200
bossbar set unmd:horsebones/horseman color pink
bossbar set unmd:horsebones/horseman name ["",{"text":"Horseman","color":"white"}]
