#######
# Compiled from data/unmd/functions/horsebones.mcscript
# to .//data/unmd/functions/horsebones/particle_kill_horsebone.mcfunction
#
# Generated by Minecraft Script for 1.13
######

particle minecraft:explosion ~ ~1 ~ 0.3 0.3 0.3 0 6
particle minecraft:witch ~ ~1 ~ 0.3 0.3 0.3 0 15
particle minecraft:explosion_emitter ~ ~1 ~ 0.3 0.3 0.3 0 1
playsound minecraft:entity.skeleton_horse.death hostile @a[distance=..20] ~ ~ ~ 10
