#######
# Compiled from data/unmd/functions/horsebones.mcscript
# to .//data/unmd/functions/horsebones/particle_upgrade_saddle.mcfunction
#
# Generated by Minecraft Script for 1.13
######

particle minecraft:witch ~ ~1 ~ 0.3 0.3 0.3 0 25
playsound minecraft:entity.elder_guardian.curse player @s ~ ~ ~ 1 0.6
