#######
# Compiled from data/unmd/functions/horsebones.mcscript
# to .//data/unmd/functions/horsebones/particle_summon_horsebone_detection.mcfunction
#
# Generated by Minecraft Script for 1.13
######

execute as @e[type=skeleton_horse,tag=horsebones_horsebone_getspawnparticle] at @s run function unmd:horsebones/particle_summon_horsebone
