#######
# Compiled from data/unmd/functions/horsebones.mcscript
# to .//data/unmd/functions/horsebones/summon_horsebone.mcfunction
#
# Generated by Minecraft Script for 1.13
######

kill @s
summon skeleton_horse ~ ~ ~ {Silent:1b,SaddleItem: {id: "minecraft:saddle", Count: 1b, tag: {ench: [{lvl: 1, id: 70}], HideFlags: 1, display: {Lore: ["Drop this to get Horsebone", "Take this saddle out to make Horsebone dissapear"], Name: "{\"translate\":\"Saddle of Summoning\",\"italic\":false}"}}},DeathLootTable:"unmd:horsebones/entities/horsebone_drop",PersistenceRequired:1b,NoAI:1b,CanPickUpLoot:0b,Health:30f,Tame:1b,Tags:["horsebones_horsebone_main","horsebones_horsebone_getspawnparticle"],Attributes:[{Name:generic.maxHealth,Base:30},{Name:generic.movementSpeed,Base:0.3375},{Name:horse.jumpStrength,Base:1.1}]}
