#######
# Compiled from data/unmd/functions/horsebones.mcscript
# to .//data/unmd/functions/horsebones/tick.mcfunction
#
# Generated by Minecraft Script for 1.13
######

function unmd:horsebones/summon_horsebone_detection
function unmd:horsebones/kill_horsebone_detection
function unmd:horsebones/particle_summon_horsebone_detection
function unmd:horsebones/saddle_os_og
function unmd:horsebones/execute_as_horsebone
function unmd:horsebones/horsebone_invisible
function unmd:horsebones/horsebone_ai
function unmd:horsebones/horseman/swap
function unmd:horsebones/horseman/detect
function unmd:horsebones/horseman/bossbar
function unmd:horsebones/horseman/player_effects