#######
# Compiled from data/unmd/functions/travel.mcscript
# to .//data/unmd/functions/travel/load.mcfunction
#
# Generated by Minecraft Script for 1.13
######

#These commands run on reload once

scoreboard objectives add UNMDtravel1 minecraft.custom:minecraft.sneak_time
scoreboard objectives add UNMDtravel2 dummy
scoreboard objectives add UNMDtravel3 dummy
scoreboard objectives add UNMDtravel4 minecraft.custom:minecraft.aviate_one_cm
scoreboard objectives add UNMDtravel5 minecraft.custom:minecraft.jump
scoreboard objectives add UNMDtravel6 dummy
scoreboard objectives add UNMDtravel7 minecraft.used:minecraft.ender_pearl
