#######
# Compiled from data/unmd/functions/travel.mcscript
# to .//data/unmd/functions/travel/tick.mcfunction
#
# Generated by Minecraft Script for 1.13
######

#These commands run every tick

#RECIPES
execute as @e[type=armor_stand,tag=advancedcrafting_main] at @s run function unmd:travel/recipes
#MECHANICS
function unmd:travel/mechanics
