#######
# Compiled from data/unmd/functions/compass_plus.mcscript
# to .//data/unmd/functions/compass_plus/detect.mcfunction
#
# Generated by Minecraft Script for 1.13
######

execute as @a run execute store result score @s xpos run data get entity @s Pos[0] 1
execute as @a run execute store result score @s ypos run data get entity @s Pos[1] 1
execute as @a run execute store result score @s zpos run data get entity @s Pos[2] 1
execute as @a run execute store result score @s xrot run data get entity @s Rotation[0] 1
