#######
# Compiled from data/unmd/functions/compass_plus.mcscript
# to .//data/unmd/functions/compass_plus/load.mcfunction
#
# Generated by Minecraft Script for 1.13
######

#Commands run every reload once
