#######
# Compiled from data/unmd/functions/compass_plus.mcscript
# to .//data/unmd/functions/compass_plus/tick.mcfunction
#
# Generated by Minecraft Script for 1.13
######

function unmd:compass_plus/detect
function unmd:compass_plus/show