#######
# Compiled from data/unmd/functions/bedtime.mcscript
# to .//data/unmd/functions/bedtime/action.mcfunction
#
# Generated by Minecraft Script for 1.13
######

execute if score playerssleeping% unmd.bedtime >= playersrequired% unmd.bedtime run execute as @a[nbt={Sleeping:1b}] run effect give @s minecraft:regeneration 1 10 true
execute if score playerssleeping% unmd.bedtime >= playersrequired% unmd.bedtime run execute unless score playersonline unmd.bedtime = 1 unmd.numbers run advancement grant @a only unmd:bedtime/morning
execute if score playerssleeping% unmd.bedtime >= playersrequired% unmd.bedtime run execute unless score playersonline unmd.bedtime = 1 unmd.numbers run time set 0
execute if score playerssleeping% unmd.bedtime >= playersrequired% unmd.bedtime run execute unless score playersonline unmd.bedtime = 1 unmd.numbers run weather clear 99999

execute if score playerssleeping unmd.bedtime = 0 unmd.numbers unless score playersonline unmd.bedtime = 1 unmd.numbers run advancement revoke @a only unmd:bedtime/morning
