#######
# Compiled from data/unmd/functions/bedtime.mcscript
# to .//data/unmd/functions/bedtime/tick.mcfunction
#
# Generated by Minecraft Script for 1.13
######

function unmd:bedtime/calc
function unmd:bedtime/detectsleeping
function unmd:bedtime/action