#######
# Compiled from data/unmd/functions/advancedcrafting_lib.mcscript
# to .//data/unmd/functions/advancedcrafting_lib/destroy.mcfunction
#
# Generated by Minecraft Script for 1.13
######

#Destroy function

summon item ~ ~ ~ {Item:{id:"iron_block",Count:8b}}
summon item ~ ~ ~ {Item:{id:"crafting_table",Count:1b}}
kill @s
