#######
# Compiled from data/unmd/functions/advancedcrafting_lib.mcscript
# to .//data/unmd/functions/advancedcrafting_lib/example_recipe.mcfunction
#
# Generated by Minecraft Script for 1.13
######

#An example example recipe

execute if block ~ ~ ~ minecraft:dropper[facing=down]{CustomName: "{"text":"Advanced Crafting Table"}", Items: [{Slot: 0b, id: "minecraft:iron_ingot", Count: 1b}, {Slot: 1b, id: "minecraft:iron_ingot", Count: 1b}, {Slot: 2b, id: "minecraft:iron_ingot", Count: 1b}, {Slot: 3b, id: "minecraft:iron_ingot", Count: 1b}, {Slot: 4b, id: "minecraft:iron_ingot", Count: 1b}, {Slot: 5b, id: "minecraft:iron_ingot", Count: 1b}, {Slot: 6b, id: "minecraft:iron_ingot", Count: 1b}, {Slot: 7b, id: "minecraft:iron_ingot", Count: 1b}, {Slot: 8b, id: "minecraft:iron_ingot", Count: 1b}], id: "minecraft:dropper"} run particle effect ~ ~ ~ 0.1 0.1 0.1 .0008 100
execute if block ~ ~ ~ minecraft:dropper[facing=down]{CustomName: "{"text":"Advanced Crafting Table"}", Items: [{Slot: 0b, id: "minecraft:iron_ingot", Count: 1b}, {Slot: 1b, id: "minecraft:iron_ingot", Count: 1b}, {Slot: 2b, id: "minecraft:iron_ingot", Count: 1b}, {Slot: 3b, id: "minecraft:iron_ingot", Count: 1b}, {Slot: 4b, id: "minecraft:iron_ingot", Count: 1b}, {Slot: 5b, id: "minecraft:iron_ingot", Count: 1b}, {Slot: 6b, id: "minecraft:iron_ingot", Count: 1b}, {Slot: 7b, id: "minecraft:iron_ingot", Count: 1b}, {Slot: 8b, id: "minecraft:iron_ingot", Count: 1b}], id: "minecraft:dropper"} run data merge block ~ ~ ~ {Items: [{Slot: 0b, id: "air", Count: 1b}, {Slot: 1b, id: "air", Count: 1b}, {Slot: 2b, id: "air", Count: 1b}, {Slot: 3b, id: "air", Count: 1b}, {Slot: 4b, id: "minecraft:iron_block", Count: 1b}, {Slot: 5b, id: "air", Count: 1b}, {Slot: 6b, id: "air", Count: 1b}, {Slot: 7b, id: "air", Count: 1b}, {Slot: 8b, id: "air", Count: 1b}]}

