#######
# Compiled from data/unmd/functions/advancedcrafting_lib.mcscript
# to .//data/unmd/functions/advancedcrafting_lib/tick.mcfunction
#
# Generated by Minecraft Script for 1.13
######

#These commands run every tick

function unmd:advancedcrafting_lib/detect
execute as @e[type=armor_stand,tag=advancedcrafting_main] at @s run execute unless block ~ ~ ~ minecraft:dropper run function unmd:advancedcrafting_lib/destroy
execute as @e[type=armor_stand,tag=advancedcrafting_main] at @s run function unmd:advancedcrafting_lib/example_recipe
