#######
# Compiled from data/unmd/functions/advancedcrafting_lib.mcscript
# to .//data/unmd/functions/advancedcrafting_lib.mcfunction
#
# Generated by Minecraft Script for 1.13
######


#Destroy function

summon item ~ ~ ~ {Item:{id:"iron_block",Count:8b}}
summon item ~ ~ ~ {Item:{id:"crafting_table",Count:1b}}
kill @s

#Detect function

execute at @a positioned ~ ~-1 ~ if block ~ ~ ~ minecraft:dropper{Items: [{Slot: 0b, id: "minecraft:iron_block", Count: 1b}, {Slot: 1b, id: "minecraft:iron_block", Count: 1b}, {Slot: 2b, id: "minecraft:iron_block", Count: 1b}, {Slot: 3b, id: "minecraft:iron_block", Count: 1b}, {Slot: 4b, id: "minecraft:crafting_table", Count: 1b}, {Slot: 5b, id: "minecraft:iron_block", Count: 1b}, {Slot: 6b, id: "minecraft:iron_block", Count: 1b}, {Slot: 7b, id: "minecraft:iron_block", Count: 1b}, {Slot: 8b, id: "minecraft:iron_block", Count: 1b}]} align xyz run summon armor_stand ~0.5 ~ ~0.5 {NoGravity:1b,Invulnerable:1b,Small:1b,Marker:1b,Invisible:1b,NoBasePlate:1b,PersistenceRequired:1b,Tags:["advancedcrafting_main","advancedcrafting_main_new"]}
execute as @e[type=armor_stand,tag=advancedcrafting_main,tag=advancedcrafting_main_new] at @s run function unmd:advancedcrafting_lib/init

#An example example recipe

execute if block ~ ~ ~ minecraft:dropper[facing=down]{CustomName: "{"text":"Advanced Crafting Table"}", Items: [{Slot: 0b, id: "minecraft:iron_ingot", Count: 1b}, {Slot: 1b, id: "minecraft:iron_ingot", Count: 1b}, {Slot: 2b, id: "minecraft:iron_ingot", Count: 1b}, {Slot: 3b, id: "minecraft:iron_ingot", Count: 1b}, {Slot: 4b, id: "minecraft:iron_ingot", Count: 1b}, {Slot: 5b, id: "minecraft:iron_ingot", Count: 1b}, {Slot: 6b, id: "minecraft:iron_ingot", Count: 1b}, {Slot: 7b, id: "minecraft:iron_ingot", Count: 1b}, {Slot: 8b, id: "minecraft:iron_ingot", Count: 1b}], id: "minecraft:dropper"} run particle effect ~ ~ ~ 0.1 0.1 0.1 .0008 100
execute if block ~ ~ ~ minecraft:dropper[facing=down]{CustomName: "{"text":"Advanced Crafting Table"}", Items: [{Slot: 0b, id: "minecraft:iron_ingot", Count: 1b}, {Slot: 1b, id: "minecraft:iron_ingot", Count: 1b}, {Slot: 2b, id: "minecraft:iron_ingot", Count: 1b}, {Slot: 3b, id: "minecraft:iron_ingot", Count: 1b}, {Slot: 4b, id: "minecraft:iron_ingot", Count: 1b}, {Slot: 5b, id: "minecraft:iron_ingot", Count: 1b}, {Slot: 6b, id: "minecraft:iron_ingot", Count: 1b}, {Slot: 7b, id: "minecraft:iron_ingot", Count: 1b}, {Slot: 8b, id: "minecraft:iron_ingot", Count: 1b}], id: "minecraft:dropper"} run data merge block ~ ~ ~ {Items: [{Slot: 0b, id: "air", Count: 1b}, {Slot: 1b, id: "air", Count: 1b}, {Slot: 2b, id: "air", Count: 1b}, {Slot: 3b, id: "air", Count: 1b}, {Slot: 4b, id: "minecraft:iron_block", Count: 1b}, {Slot: 5b, id: "air", Count: 1b}, {Slot: 6b, id: "air", Count: 1b}, {Slot: 7b, id: "air", Count: 1b}, {Slot: 8b, id: "air", Count: 1b}]}


#Initialisation

tag @s remove advancedcrafting_main_new
data merge block ~ ~ ~ {Items: [{Slot: 0b, id: "minecraft:air", Count: 1b}, {Slot: 1b, id: "minecraft:air", Count: 1b}, {Slot: 2b, id: "minecraft:air", Count: 1b}, {Slot: 3b, id: "minecraft:air", Count: 1b}, {Slot: 4b, id: "minecraft:air", Count: 1b}, {Slot: 5b, id: "minecraft:air", Count: 1b}, {Slot: 6b, id: "minecraft:air", Count: 1b}, {Slot: 7b, id: "minecraft:air", Count: 1b}, {Slot: 8b, id: "minecraft:air", Count: 1b}]}
setblock ~ ~ ~ minecraft:dropper[facing=down]{CustomName:"{\"text\":\"Advanced Crafting Table\"}"} replace
particle minecraft:flame ~ ~.5 ~ 0 0 0 .1 200

#These commands run every tick

function unmd:advancedcrafting_lib/detect
execute as @e[type=armor_stand,tag=advancedcrafting_main] at @s run execute unless block ~ ~ ~ minecraft:dropper run function unmd:advancedcrafting_lib/destroy
execute as @e[type=armor_stand,tag=advancedcrafting_main] at @s run function unmd:advancedcrafting_lib/example_recipe

#These commands run one reload once
