#######
# Compiled from data/unmd/functions/horsebones.mcscript
# to .//data/unmd/functions/horsebones/rituals/ritual_5.mcfunction
#
# Generated by Minecraft Script for 1.13
######

advancement revoke @s only unmd:horsebones/detection_ritual_5
advancement grant @s only unmd:horsebones/ritual_5 kill
tag @s add horsebones_player_hashorsebone
