#######
# Compiled from data/unmd/functions/horsebones.mcscript
# to .//data/unmd/functions/horsebones/horseman/bossbar.mcfunction
#
# Generated by Minecraft Script for 1.13
######

execute if entity @e[type=minecraft:stray,tag=horsebones_horseman_main] run bossbar set unmd:horsebones/horseman visible true
execute if entity @e[type=minecraft:stray,tag=horsebones_horseman_main] run bossbar set unmd:horsebones/horseman players @a
execute unless entity @e[type=minecraft:stray,tag=horsebones_horseman_main] run bossbar set unmd:horsebones/horseman visible false
execute as @e[type=minecraft:stray,tag=horsebones_horseman_main] store result bossbar unmd:horsebones/horseman value run data get entity @e[type=minecraft:stray,tag=horsebones_horseman_main,limit=1] Health 1
