#######
# Compiled from data/unmd/functions/horsebones.mcscript
# to .//data/unmd/functions/horsebones/horseman/detect.mcfunction
#
# Generated by Minecraft Script for 1.13
######

execute unless entity @e[type=stray,tag=horsebones_horseman_main] as @e[type=horse,nbt={SaddleItem: {id: "minecraft:saddle", Count: 1b, tag: {ench: [{Lvl: 1, Id: 70}], HideFlags: 1, display: {Lore: ["A powerful saddle bursting with arcane energy.", "Putting this on a horse could kill it... (IV of IV)"], Name: "{\"text\":\"Imbued Saddle\",\"italic\":false}"}}}}] at @s run function unmd:horsebones/horseman/summon_setup
