#######
# Compiled from data/unmd/functions/horsebones.mcscript
# to .//data/unmd/functions/horsebones/horseman/player_effects.mcfunction
#
# Generated by Minecraft Script for 1.13
######

execute at @e[type=minecraft:stray,tag=horsebones_horseman_main] run effect give @a[distance=..10] minecraft:speed 1 4 true
