#######
# Compiled from data/unmd/functions/horsebones.mcscript
# to .//data/unmd/functions/horsebones/horseman/summon_visuals.mcfunction
#
# Generated by Minecraft Script for 1.13
######

particle minecraft:explosion ~ ~1 ~ 0.3 0.3 0.3 0 6
particle minecraft:witch ~ ~1 ~ 0.3 0.3 0.3 0 15
particle minecraft:explosion_emitter ~ ~1 ~ 0.3 0.3 0.3 0 1
