#######
# Compiled from data/unmd/functions/horsebones.mcscript
# to .//data/unmd/functions/horsebones/horseman/summon.mcfunction
#
# Generated by Minecraft Script for 1.13
######

summon stray ~ ~ ~ {DeathLootTable:"unmd:horsebones/entities/horseman_drop",PersistenceRequired:1b,Health:200f,Tags:["horsebones_horseman_main","horsebones_horseman_summon"],CustomName:"{\"text\":\"Horseman\"}",HandItems:[{id:"minecraft:iron_axe",Count:1b,tag:{HideFlags:1,ench:[{id:71,lvl:1}],AttributeModifiers:[{AttributeName:"generic.attackDamage",Name:"generic.attackDamage",Amount:10,Operation:0,UUIDLeast:855438,UUIDMost:598429}]}},{id:"minecraft:bow",Count:1b,tag:{HideFlags:1,ench:[{id:71,lvl:1}]}}],HandDropChances:[-327.67F,-327.67F],ArmorItems:[{},{},{},{id:"minecraft:carved_pumpkin",Count:1b,tag:{ench:[{id:71,lvl:1}],AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"generic.movementSpeed",Amount:0.1,Operation:0,UUIDLeast:843656,UUIDMost:270523,Slot:"head"}]}}],ArmorDropChances:[0.85F,0.85F,0.85F,-327.67F],Attributes:[{Name:generic.maxHealth,Base:200},{Name:generic.followRange,Base:50},{Name:generic.knockbackResistance,Base:0.99},{Name:generic.attackDamage,Base:7}]}
execute positioned ~ ~1 ~ run particle minecraft:sweep_attack ^ ^ ^.3 0.3 0.3 0.3 0 1
execute positioned ~ ~1 ~ run particle minecraft:witch ~ ~ ~ 0.3 0.3 0.3 0 10
playsound minecraft:entity.player.small_fall hostile @a ~ ~ ~
