#######
# Compiled from data/unmd/functions/horsebones.mcscript
# to .//data/unmd/functions/horsebones/horseman/swap.mcfunction
#
# Generated by Minecraft Script for 1.13
######

execute as @e[type=stray,tag=horsebones_horseman_main] run scoreboard players add @s hbs_man_swap 1
execute as @e[type=stray,tag=horsebones_horseman_main,scores={hbs_man_swap=200}] at @s run replaceitem entity @s weapon.mainhand minecraft:bow{HideFlags:1,ench:[{id:71,lvl:1}],AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"generic.movementSpeed",Amount:1,Operation:1,UUIDLeast:843656,UUIDMost:270523,Slot:"head"}]}
execute as @e[type=stray,tag=horsebones_horseman_main,scores={hbs_man_swap=200}] at @s run replaceitem entity @s weapon.offhand minecraft:iron_axe{HideFlags:1,ench:[{id:71,lvl:1}],AttributeModifiers:[{AttributeName:"generic.attackDamage",Name:"generic.attackDamage",Amount:10,Operation:0,UUIDLeast:855438,UUIDMost:598429}]}
execute as @e[type=stray,tag=horsebones_horseman_main,scores={hbs_man_swap=200}] at @s run function unmd:horsebones/horseman/swap_visuals
execute as @e[type=stray,tag=horsebones_horseman_main,scores={hbs_man_swap=200}] at @s run run replaceitem entity @s weapon.offhand minecraft:bow{HideFlags:1,ench:[{id:71,lvl:1}]}
execute as @e[type=stray,tag=horsebones_horseman_main,scores={hbs_man_swap=200}] at @s run run replaceitem entity @s weapon.mainhand minecraft:iron_axe{HideFlags:1,ench:[{id:71,lvl:1}],AttributeModifiers:[{AttributeName:"generic.attackDamage",Name:"generic.attackDamage",Amount:10,Operation:0,UUIDLeast:855438,UUIDMost:598429}]}
execute as @e[type=stray,tag=horsebones_horseman_main,scores={hbs_man_swap=200}] at @s run function unmd:horsebones/horseman/swap_visuals
execute as @e[type=stray,tag=horsebones_horseman_main,scores={hbs_man_swap=200}] at @s run scoreboard players set @s hbs_man_swap 0
