#######
# Compiled from data/unmd/functions/horsebones.mcscript
# to .//data/unmd/functions/horsebones/horseman/swap_visuals.mcfunction
#
# Generated by Minecraft Script for 1.13
######

execute positioned ~ ~1 ~ run particle minecraft:sweep_attack ^ ^ ^.3 0.3 0.3 0.3 0 1
execute positioned ~ ~1 ~ run particle minecraft:witch ~ ~ ~ 0.3 0.3 0.3 0 10
playsound minecraft:entity.player.small_fall hostile @a ~ ~ ~